package Pojo;
// Generated 23/03/2016 06:56:21 PM by Hibernate Tools 4.3.1



/**
 * Publicar generated by hbm2java
 */
public class Publicar  implements java.io.Serializable {


     private int idpublicar;
     private String descripcion;

    public Publicar() {
    }

	
    public Publicar(int idpublicar) {
        this.idpublicar = idpublicar;
    }
    public Publicar(int idpublicar, String descripcion) {
       this.idpublicar = idpublicar;
       this.descripcion = descripcion;
    }
   
    public int getIdpublicar() {
        return this.idpublicar;
    }
    
    public void setIdpublicar(int idpublicar) {
        this.idpublicar = idpublicar;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


