package Pojo;
// Generated 23/03/2016 06:56:21 PM by Hibernate Tools 4.3.1



/**
 * UsuarioPublicar generated by hbm2java
 */
public class UsuarioPublicar  implements java.io.Serializable {


     private UsuarioPublicarId id;

    public UsuarioPublicar() {
    }

    public UsuarioPublicar(UsuarioPublicarId id) {
       this.id = id;
    }
   
    public UsuarioPublicarId getId() {
        return this.id;
    }
    
    public void setId(UsuarioPublicarId id) {
        this.id = id;
    }




}


