package Pojo;
// Generated 23/03/2016 06:56:21 PM by Hibernate Tools 4.3.1



/**
 * UsuarioPublicarId generated by hbm2java
 */
public class UsuarioPublicarId  implements java.io.Serializable {


     private int usuarioidusuario;
     private int publicaridpublicar;

    public UsuarioPublicarId() {
    }

    public UsuarioPublicarId(int usuarioidusuario, int publicaridpublicar) {
       this.usuarioidusuario = usuarioidusuario;
       this.publicaridpublicar = publicaridpublicar;
    }
   
    public int getUsuarioidusuario() {
        return this.usuarioidusuario;
    }
    
    public void setUsuarioidusuario(int usuarioidusuario) {
        this.usuarioidusuario = usuarioidusuario;
    }
    public int getPublicaridpublicar() {
        return this.publicaridpublicar;
    }
    
    public void setPublicaridpublicar(int publicaridpublicar) {
        this.publicaridpublicar = publicaridpublicar;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioPublicarId) ) return false;
		 UsuarioPublicarId castOther = ( UsuarioPublicarId ) other; 
         
		 return (this.getUsuarioidusuario()==castOther.getUsuarioidusuario())
 && (this.getPublicaridpublicar()==castOther.getPublicaridpublicar());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioidusuario();
         result = 37 * result + this.getPublicaridpublicar();
         return result;
   }   


}


